### PR TITLE
Support drill down within a facet

### LINKED ISSUE #336: Improve behaviour when classification notation is chosen
Reported by H.F. via email on 2016-07-27:

> während der Arbeiten am Artikel fielen mir noch zwei Dinge zur
> Systematiksuche auf. Einmal bricht nach der Anwahl einer Systemstelle
> die Nutzerinformation über die ausgeführte Suche ab. Könnte man hier
> analog zu anderen Suchen oberhalb der Treffer die für die Trefferanzeige
> relevante Systemstelle anzeigen z.B. "Sachgebiet" und dann "402340
> Grundrechte"?
> 
> Das andere ist die Facette "Sachgebiete" nach Auswahl einer
> Systemstelle. Hier steht die formale Info, dass man eine Stelle
> ausgewählt hat, das ist in Ordnung. Dann werden aber stets nach jeder
> Systemstellenauswahl dieselben Sachgebiete beginnend mit "Geschichte
> (23307)" genannt. Da man nach Auswahl einer einzelnen Systemstelle die
> gefundenen Titel allerdings mit anderen Systemstellen nicht weiter
> einzugrenzen vermag, müssten der Hinweis "1 ausgewählt" eigentlich
> reichen und die weiteren Hinweise auf Systemstellen entfallen.
>

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #336

Include current facet selection when getting other facet values. Makes the facet self restricting: it shows only values that appear with the current selection. Makes the facet behavior more consistent, as facets in general narrow down the current results.

Also fixes the problem of missing selected values which were not part of the top results with the previous behavior.

### CODE REVIEW

**Comment by dr0i** [comment]
Failing check, reassigning.

**Comment by fsteeg** [comment]
Rebased on top of separate CI and non-CI test suites, see https://github.com/hbz/nwbib/commit/0da67b1efea5b391bcedda2676eb62ba233ffc0c.

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Don't know what to do with this, reassigning @fsteeg .

**Comment by fsteeg** [comment]
Weird, didn't touch this, just merged from server, must have been assigned automatically.

**Pull request merged**
