### PR TITLE
Update about link and footer icons (#652)

### LINKED ISSUE #652: Link zur Landesbibliotheken-Seite aktualisieren, Logo ergänzen
Am 05.09.24 um 09:44 schrieb @HMetzner:

> die Landesbibliotheken NRW haben eine neue Homepage erhalten: 
> https://www.landesbibliotheken.nrw/ . Daher müsste ein Link angepasst 
> werden und wir würden gerne das Logo der LB einbauen.
> 
> Kannst du diesen Link bitte dort einbauen, wo bisher auf die alte Seite 
> der LB verlinkt wurde (s. Screenshot)? Der Linktext sollte dann heißen 
> „Über die Landesbibliotheken“.
> 
> Mit den neuen Seiten der LB ging auch einher ein gemeinsames Logo zu 
> entwickeln, um die Produkte der LB auszuweisen. Das Logo würden wir 
> gerne unten auf der Startseite der NWBib präsentieren (s. Anhang).
> 
> Da ist die Frage, ob man es unten mittig unter den Kasten oder in den 
> Kasten einbauen kann (inkl. Verlinkung auf die Startseite 
> https://www.landesbibliotheken.nrw/ 
> <https://www.landesbibliotheken.nrw/>)? Mock-up siehe Anhang.

Logo_LB_NWBib_Entwurf

Landesbibliotheken_NRW

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #652.

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed to test: https://test.nwbib.de/

**Comment by acka47** [comment]
https://test.nwbib.de/ seems to be down?

**Comment by fsteeg** [comment]
It's back: https://test.nwbib.de/

**Review by acka47 — APPROVED** [review]
+1

**Pull request merged**
