### PR TITLE
Move narrower entries of 52/72 under 54/74

### LINKED ISSUE #504: Set up update process for spatial classification
On 05.11.19 17:05, I.N. wrote:
> es gibt neue Ortsteile, die noch nicht in der NWBib-Raumsystematik 
> angezeigt werden, weil sie noch nicht in die SKOS-Datei übernommen wurden.
> 
> Es handelt sich um:
> 
> 1.Langeland (Ortsteil von Bad Driburg) siehe 
> https://nwbib.de/HT020213557 <https://nwbib.de/HT020213557>
> 
> 2.Schallern (Ortsteil von Erwitte) siehe https://nwbib.de/HT018868330

So there are at least these two entries in Wikidata ([Q1804946](https://www.wikidata.org/wiki/Q1804946), [Q2230503](https://www.wikidata.org/wiki/Q2230503)) that recently had the NWBib-ID (P6814) added. Taking a look at [sparql_rc](https://tools.wmflabs.org/wikidata-todo/sparql_rc.php?sparql=SELECT+DISTINCT%0D%0A%3Fq%0D%0AWHERE+%7B%0D%0A++%3Fq+wdt%3AP6814+%3FnwbibId.+%7D&start=20191019&end=20191106&user_lang=de&sort_mode=last_edit) there is one more:

- [Oelgershausen (Q1528807)](https://www.wikidata.org/wiki/Q1528807)

We should add them to the classification and by doing so try out a process for updating the classification from Wikidata.

### PR DESCRIPTION
**Pull request by acka47**
Fixes https://github.com/hbz/nwbib/issues/503 and delivers parts for https://github.com/hbz/nwbib/issues/502. Should also fix #504.

### CODE REVIEW

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/commit/ff19adb5647e136c0c475017535c0cf5fb2f94c1

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/commit/25354789f079266a9af51c4bbc60fc32a429c0c5

**Comment by acka47** [comment]
As mentioned in #504, to three new places in Wikidata, a NWBib ID was added and they are also used in cataloging:

1. Oelgershausen ([Q1528807](https://www.wikidata.org/wiki/Q1528807)), see http://lobid.org/resources/HT020155665.json
2. Langeland ([Q1804946](https://www.wikidata.org/wiki/Q1804946)), see http://lobid.org/resources/HT020213557.json
3. Schallern ([Q2230503](https://www.wikidata.org/wiki/Q2230503)), see http://lobid.org/resources/HT018868330.json

Strangely, only one of those (2. Langeland) is added to the SKOS file by the linked commit. Why not the other two?

**Comment by fsteeg** [comment]
> Strangely, only one of those (2. Langeland) is added to the SKOS file by the linked commit.

Hm, so actually none should have been added at this point, since we did not update from Wikidata.

Maybe Langeland was already in the Wikidata state we used, but only now used in the catalog?

**Comment by acka47** [comment]
> Maybe Langeland was already in the Wikidata state we used, but only now used in the catalog?

NWBib-ID for Langeland (Q1804946) was added on 2019-10-24: https://www.wikidata.org/w/index.php?title=Q1804946&type=revision&diff=1038184245&oldid=1038183382, sames as for Oelgershausen (https://www.wikidata.org/w/index.php?title=Q1528807&type=revision&diff=1038139289&oldid=1029147613).

Schallern got an NWBib-ID already on 2019-10-15, see https://www.wikidata.org/w/index.php?title=Q2230503&type=revision&diff=1032312364&oldid=998515694

So this can not be the reason.

**Comment by fsteeg** [comment]
I checked the test deployment data, and in that, of these three, only Langeland has `partOf` information.

**Comment by fsteeg** [comment]
Deployed with current Wikidata:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/commit/1f25c552915ae6bf52b2c8d2b436f6d242dc1d83 (letzte)
https://github.com/hbz/lobid-vocabs/pull/104/files (alle aktuellen)

**Comment by acka47** [comment]
Looks good except of one thing: Why is "Kreis Lemgo" (Q1543152) removed although the wikidata entry has an NWBib-ID (see https://www.wikidata.org/wiki/Q1543152) and there is one lobid resource that has it in `spatial`, see  https://lobid.org/resources/HT017077527.json?

**Comment by fsteeg** [comment]
> Why is "Kreis Lemgo" (Q1543152) removed

Hm, this might be caused by the missing `broader` in https://www.wikidata.org/wiki/Q7923.

Not sure why it was in the SKOS file before though.

**Comment by fsteeg** [comment]
Not sure why, but when I re-generate the SKOS file, Kreis Lemgo is in:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/commit/53b2abf93dfa329622726729128b0f1d4e50831e
https://github.com/hbz/lobid-vocabs/pull/104/files

**Comment by acka47** [comment]
+1 This looks good now.

**Comment by acka47** [comment]
I forgot to remove 72 from the conf file and did so today after H.F. notified us via the mailing list.

**Comment by fsteeg** [comment]
Deployed to test:

https://test.nwbib.de/spatial
https://github.com/hbz/lobid-vocabs/pull/104/commits/2c47c412777ce577b2cfb1ad5a84d662f5552ed4
https://github.com/hbz/lobid-vocabs/pull/104/files

**Comment by acka47** [comment]
+1

**Pull request merged**
