### PR TITLE
Add Gräfrath to spatial conf

### LINKED ISSUE #558: Entferne Zusatz "Stadtbezirk" bei Solingen-Gräfrath
Reported on 2020-11-30 by U.P.:

> bei Solingen gibt es noch einen Stadtteil, nämlich Gräfrath, der in der 
> NWBib-Systematik noch den Zusatz „Stadtbezirk“ trägt. In Wikidata ist 
> das Label nur „Gräfrath“. Ich vermute, man muss den Zusatz händisch 
> löschen in der Systematik, nicht wahr? Bei Solingen hatten wir uns dafür 
> entschieden, die Untergliederung nach Stadtbezirken wegzulassen.

### PR DESCRIPTION
**Pull request by acka47**
Resolves #558

### CODE REVIEW

**Comment by fsteeg** [comment]
Hm, I'm a bit confused: https://www.wikidata.org/wiki/Q326089 does not have "Stadtbezirk", so we want it as it is on Wikidata, right? Then we should not have to add it as a special case to the conf file, do we? I also tried reloading test from Wikidata but it still has "Stadtbezirk", I think changing existing labels did not work with that yet. Would have to investigate, if that makes sense and I'm not missing something here about adding it to the conf.

**Comment by acka47** [comment]
> https://www.wikidata.org/wiki/Q326089 does not have "Stadtbezirk", so we want it as it is on Wikidata, right? 

As of #525, we add "Stadtbezirk" in parenthesis when something has Q2740635 as type (P31) but in this case we want to bypass this rule, thus, I added it to the conf. (This is very similar to #551.)

**Comment by fsteeg** [comment]
Deployed to test, see:

https://test.nwbib.de/spatial#Q326089
https://github.com/hbz/lobid-vocabs/pull/126/files

**Comment by acka47** [comment]
+1

**Pull request merged**
