### PR TITLE
Documentation of NWBib searches

### PR DESCRIPTION
**Pull request by ChristophEwertowski**
See https://github.com/hbz/lobid-resources/issues/708

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
@acka47 : Probably you also want to have a look. If it's O.K., merge it.

**Comment by acka47** [comment]
I did some smal changes. +1

**Comment by ChristophEwertowski** [comment]
+1 For your changes.

**Comment by ChristophEwertowski** [comment]
As the Travis checks are now successful, I'm merging it.

**Pull request merged**
