### PR TITLE
Add journal list and data

### LINKED ISSUE #337: Add journal list to web site
Requested by customers via email from I.N. on 2016-08-05:

> im Anhang finden Sie die Liste der laufend für die
> Nordrhein-Westfälische Bibliographie ausgewerteten Zeitschriften.
> 
> Diese Liste war bisher an folgender Stelle zu finden:
> 
> http://www.landesbibliothek-nrw.de/aufgaben/nrw_bibliographie/zeitschriftenliste/
> 
> Die Zeitschriftentitel enthalten noch den Link zur alten NWBib.
> 
> In Absprache mit der NWBib-Redaktion in Düsseldorf, haben wir die
> Zeitschriftenliste aktualisiert und die Links korrigiert.
> 
> Die Links führen nun zur neuen Web-Version der NWBib.
> 
> Gemeinsam mit der Redaktion in Düsseldorf haben wir überlegt, wo die
> Zeitschriftenliste in der Web-Version eingebunden werden könnte.
> 
> Wir haben uns auf folgende Position geeinigt: Die Liste sollte in der
> obersten Zeile innerhalb des Menüs mit dem Informationssymbol als
> eigener Eintrag unterhalb von „Über die NWBib“ positioniert werden (s. u.).
> 
> Der Eintrag sollte lauten: „Ausgewertete Zeitschriften“.

nwbib-journal-list

I forwarded the mail with attachment (xslx) to @fsteeg .

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #337

### CODE REVIEW

**Comment by dr0i** [comment]
Failing check, reassigning.

**Comment by fsteeg** [comment]
Rebased on top of separate CI and non-CI test suites, see https://github.com/hbz/nwbib/commit/0da67b1efea5b391bcedda2676eb62ba233ffc0c.

**Comment by dr0i** [comment]
+1

**Comment by dr0i** [comment]
Don't know what I shall do. Reassigning @fsteeg .

**Comment by fsteeg** [comment]
Weird, didn't touch this, just merged from server, must have been assigned automatically.

**Pull request merged**
