### PR TITLE
Update print media type URL

### LINKED ISSUE #371: URL shown for media type http://rdvocab.info/termList/RDAproductionMethod/#1010
See http://nwbib.de/HT016987883

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #371

Deployed to staging: http://test.nwbib.de/HT016987883

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
+1

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Sorry -my fault (merged hbz/lobid-resources#154 without your acknowledge).
But I wasn't aware: why do you define the labels? It's all in the data and the changing of the id (or the label) there shouldn't bother you.

**Comment by fsteeg** [comment]
Right, I was just about to comment on the issue, where you also asked this, and link to this pull request. The URIs are in the config file and mapped to a label, an icon, and a priority (which label/icon to use if we have multiple values, e.g. in result list), see diff of this pull request.

**Comment by dr0i** [comment]
In the diff I only definitions which are already done in [labels](https://github.com/hbz/lobid-rdf-to-json/blob/master/src/main/resources/labels.json#L12288) (note that you can also define an icon there). (Don't get the priority re multiple values, though.)

**Comment by fsteeg** [comment]
But we don't have an icon field in the data, right? Might be a useful addition.

The priority is used for cases where something is both `Print` and a `Map`. It defines that in a result list, where we show a single icon only, it should show the more specific `Map`, not the more general `Print` icon. See also https://github.com/hbz/nwbib/issues/113.

I agree that it would be nice to get all this information from the data, instead from a separate config file, and we can investigate that. But it is beside the point for this issue and pull request, which fixes the bug in production caused by the changed URL.

**Comment by dr0i** [comment]
+1
I bother to open a new issue "Get labels and icons from labels.json`" for you would have to implement it anyway.

If you open an issue, note that `labels.json` already supports `icon`. For the prioritization: as we only have an array with objetcs-URIs for `rdf:type` (? in any case: not many cases) this could be handled in the web apps - or with an integer for prioritization in `lables.json`).

**Comment by fsteeg** [comment]
Opened https://github.com/hbz/lobid-resources-web/issues/17.

Closing this (it's actually merged, but GitHub didn't pick that up).

**Pull request closed without merging**
