### PR TITLE
Add label and icon for ArchivedWebPage type

### LINKED ISSUE #383: Add label for type "ArchivedWebPage"
See, for example: http://nwbib.de/TT002234459 (which is actually not part of NWBib). I don't think there are any resources of type "ArchivedWebPage" in NWBib, nonetheless it should be able to display them correctly if some are added. This is probably best done when implementing API 2.0 as source of NWBib search.

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #383

See: http://test.nwbib.de/TT002234459

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
+1 for the detail view.
But it is missing as a facet in the list view.

**Comment by acka47** [comment]
As I already noted in https://github.com/hbz/nwbib/issues/383#issue-203991598, there actually aren't any resources of type ArchivedWebPage in NWBib, see http://nwbib.de/search?name=*&t=http%3A%2F%2Fpurl.org%2Flobid%2Flv%23ArchivedWebPage for proof. Thus, both the label nor the facet are of very low priority. As you have started to add the label you might as well add it to the facet, though...

**Comment by fsteeg** [comment]
> But it is missing as a facet in the list view. See search for title "jakobswege".

As @acka47 mentioned in https://github.com/hbz/nwbib/issues/383, that title is not actually part of NWBib (the UI supports displaying non-NWBib titles for debugging purpose, but they won't show up in searches). You can see the facet here: http://test.nwbib.de/search

**Comment by fsteeg** [comment]
(@acka47: not sure why the query with name yields 0, but this works:
http://test.nwbib.de/search?q=*&t=http%3A%2F%2Fpurl.org%2Flobid%2Flv%23ArchivedWebPage)

**Comment by acka47** [comment]
Good to know there are actually two archived web pages recorded in NWBib. +1 for everyhing

**Comment by ChristophEwertowski** [comment]
+1

**Comment by dr0i** [comment]
+1

**Pull request merged**
