### PR TITLE
Fix contribution links

### LINKED ISSUE #369: Contribution links broken
See `Autor/in` in: http://nwbib.de/HT013677392

### PR DESCRIPTION
**Pull request by fsteeg**
Will resolve #369

Deployed to staging: http://test.nwbib.de/HT013677392

### CODE REVIEW

**Comment by ChristophEwertowski** [comment]
Sorry, can't see a difference between test and production system in regards to contribution links. In both cases the links to the contributions of the author work fine.

**Comment by acka47** [comment]
+1 for staging and production

**Comment by fsteeg** [comment]
Re: why it was fixed in production - @dr0i deployed a change to the data that also fixed the issue (agents no longer arrays).

@dr0i: I think we should still merge this change, as the code is cleaner.

**Comment by dr0i** [comment]
I think we should keep things simple. As the data guarantees for agents not beeing an array we should get rid of unnecessary if-else. Or missed I something?

**Comment by fsteeg** [comment]
There is no additional if-else, and I think the the code is more readable, see the diff:
https://github.com/hbz/nwbib/pull/370/files

**Comment by dr0i** [comment]
Can't read scala very well ... so this is basically about reformatting the code and not about handling data coming with or without arrays? Then +1.

**Comment by fsteeg** [comment]
> so this is basically about reformatting the code and not about handling data coming with or without arrays?

It was already handling data with and without arrays for the labels, but was not using the mechanism for the IDs (which is why the links failed). The change was to fix that. In order to find that problem, I improved both the structure and the formatting of the code. We currently have many such cases throughout the code. I'll remove them all when the API is stable.

**Pull request merged**
