### PR TITLE
Remove unused types

### PR DESCRIPTION
**Pull request by acka47**
Cleanup, removing deprecated frbr:Manifestation & bibo:Document.

### CODE REVIEW

**Comment by acka47** [comment]
I adjusted all the numbering but don't know whether this is right or whether the numbers are used elsewhere to address the types...

**Comment by fsteeg** [comment]
The order is for https://github.com/hbz/nwbib/issues/113

Deployed to staging. Looks good to me: http://test.lobid.org/nwbib/search?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMultiVolumeBook

Still reassigning for review as we have no corresponding issue.

**Comment by acka47** [comment]
As far as I can see the last commit isn't yet deployed to staging. Will review as soon as this is the case.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib

**Comment by acka47** [comment]
+1

**Pull request merged**
