### PR TITLE
Migrate continuous integration from travis to github actions

### PR DESCRIPTION
**Pull request by dr0i**
- add github-actions' build.yml
- remove travis build
- rename classes to get rid of "travis"
- substitute link to travis's yml to github action's yml
- use https to resolve plugins

See #566.

### CODE REVIEW

**Comment by fsteeg** [comment]
Hm, I think labeling them as "Scala CI" is confusing. On Travis, we had configured them as "scala" builds, resulting in Travis automatically building with sbt. But here, we configure that explicitly. I think they should be called "Build" like the others.

**Comment by dr0i** [comment]
Labeling "Scala CI" I found also funny - but as mntioned in standup yesterday, this is what github proposes in its template. Now I know this labeling is arbitrary and wondering if there is some advantage in accepting github's template proposal or dumping that? What do you think?

**Comment by fsteeg** [comment]
It's just the `name: Scala CI` field in the yml, right? I think we can just change that to `name: Build`.

**Comment by dr0i** [comment]
Yes, as I wrote, we can simply change it.

**Comment by dr0i** [comment]
A good argument for naming to `Build`: we have projects which use e.g. maven and scala. So the templated name like `Scala CI` wouldn't fit there.

**Review by fsteeg — APPROVED** [review]

**Pull request merged**
